version: '3.8'

networks:
  ai-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - redis
    ports:
      - "3000:3000"
    networks:
      - ai-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nft_ai
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ai-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ai-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ai-network

volumes:
  db_data:
